# Generated by Django 5.2.7 on 2025-10-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_category_product_delete_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
